version: '3'
services:
  patroni:
    image: patroni:ahmed
    build:
      context: .
      dockerfile: ./postgres-patroni-dockerfile
    networks:
      - postgres-backend
    ports:
      - "8008:8008"
      - "6432:5432"
    user: postgres
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
    environment:
      TZ: Asia/Riyadh
      PATRONI_NAME: member_1
      PATRONI_POSTGRESQL_DATA_DIR: /var/lib/postgresql/data/node1
      PATRONI_CONSUL_HOST: http://consul-ip:8500
      PATRONI_CONSUL_URL: http://consul-ip:8500/v1/
    restart: unless-stopped

  pgbouncer:
    image: edoburu/pgbouncer   
    networks:
      - postgres-backend
    ports:
      - "5432:5432"
    depends_on:
      - patroni
    environment:
      TZ: Asia/Riyadh
      ADMIN_USERS: admin
      DB_HOST: patroni
      DB_USER: admin
      DB_PASSWORD: admin
      POOL_MODE: transaction
      MAX_CLIENT_CONN: 1000
      DEFAULT_POOL_SIZE: 300
    restart: unless-stopped
    
  consul:
    image: hashicorp/consul
    networks:
      - postgres-backend
    hostname: "${HOSTNAME}"
    environment:
      TZ: Asia/Riyadh
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8301:8301/udp"
      - "8302:8302"
      - "8302:8302/udp"
      - "8400:8400"
      - "8500:8500"
      - "8600:8600/udp"
    volumes:
      - ./volumes/consul-data:/data
    restart: unless-stopped
    command: agent -server -advertise 192.168.100.234 -bootstrap-expect 3 -client 0.0.0.0 -retry-join 192.168.100.234 -retry-join 10.128.0.98 -retry-join 10.128.0.99


networks:
  postgres-backend:
    driver: bridge
