version: '3'
services:
  patroni:
    image: patroni:latest
    build:
      context: .
      dockerfile: ./dockerfile
    network_mode: host
    ports:
      - "8008:8008"
      - "6432:5432"
    user: postgres
    volumes:
      - ../../../pg-cluster-volumes/postgres-data:/var/lib/postgresql/data
    environment:
      TZ: Asia/Riyadh
      PATRONI_NAME: member_${HOSTNAME}
      PATRONI_POSTGRESQL_DATA_DIR: /var/lib/postgresql/data/node
      PATRONI_CONSUL_HOST: http://34.194.97.9:8500
      PATRONI_CONSUL_URL: http://34.194.97.9:8500/v1/
    restart: unless-stopped

  consul-server1:
    image: hashicorp/consul:1.11.2
    container_name: consul-server1
    restart: unless-stopped
    volumes:
     - ./config/server1.json:/consul/config/server1.json
     - ./certs/:/consul/config/certs/
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -bootstrap-expect=3"
    network_mode: host

  consul-client:
    image: hashicorp/consul:1.11.2
    container_name: consul-client
    restart: unless-stopped
    volumes:
     - ./config/client.json:/consul/config/client.json
     - ./certs/:/consul/config/certs/
    command: "agent"
    network_mode: host
